import 'dart:io';

import 'package:path/path.dart' as p;

import 'failure.dart';
import 'toolchain.dart';

/// The client half of one Mana primitive: Dart for the `x-mana-*` value a
/// resource schema carries.
final class PrimitiveWriter {
  const PrimitiveWriter(this.suffix, this.write);

  /// The generated class is `<Type><suffix>` (`BookingVerbs`).
  final String suffix;

  /// The class body for [resource]'s contract [value].
  final void Function(StringBuffer out, String resource, List<Map> value) write;
}

/// Every primitive the generator knows, by contract key. A contract key
/// with no writer stops generation: a primitive is not done until its
/// client half exists.
final primitiveWriters = <String, PrimitiveWriter>{
  'x-mana-verbs': PrimitiveWriter('Verbs', _verbs),
  'x-mana-views': PrimitiveWriter('Views', _views),
  'x-mana-attachments': PrimitiveWriter('Attachments', _attachments),
  'x-mana-history': PrimitiveWriter('History', _history),
  'x-mana-entity': PrimitiveWriter('Entity', _entity),
  'x-mana-flow': PrimitiveWriter('Flow', _flow),
  'x-mana-notifications': PrimitiveWriter('Notifications', _notifications),
};

/// Writes `lib/src/primitives.dart` with one class per resource and
/// primitive (`BookingVerbs.cancel`, `BookingViews.reservationCard`,
/// `PropertyAttachments.coverPhotoId`), exports it and depends on
/// `mana_primitives`. Contracts without primitives are left untouched.
void writePrimitives(
  String stage,
  String name,
  String output,
  Object? contract,
) {
  final schemas =
      ((contract as Map?)?['components'] as Map?)?['schemas'] as Map? ??
      const {};
  final placed = <(String, String, List<Map>)>[];
  for (final MapEntry(key: resource, :value) in schemas.entries) {
    if (value is! Map) continue;
    for (final MapEntry(:key, value: declared) in value.entries) {
      if (key is! String || !key.startsWith('x-mana-')) continue;
      if (!primitiveWriters.containsKey(key)) {
        throw ManaFailure(
          'The contract carries $key on $resource but the client generator has no writer for it; add one to primitiveWriters (framework/cli/lib/src/primitives.dart).',
        );
      }
      placed.add((key, resource as String, (declared as List).cast<Map>()));
    }
  }
  if (placed.isEmpty) return;
  placed.sort(
    (a, b) => a.$2 == b.$2 ? a.$1.compareTo(b.$1) : a.$2.compareTo(b.$2),
  );
  final views = [
    for (final (key, resource, value) in placed)
      if (key == 'x-mana-views')
        for (final view in value) (resource, view),
  ];
  final out = StringBuffer()
    ..writeln(
      '// Generated by mana client generate from the x-mana-* contract keys. Do not edit.',
    )
    ..writeln(
      views.isEmpty
          ? "import 'package:mana_primitives/mana_primitives.dart';"
          : "import 'package:built_collection/built_collection.dart';\nimport 'package:$name/$name.dart';",
    )
    ..writeln()
    ..writeln("export 'package:mana_primitives/mana_primitives.dart';");
  for (final (key, resource, value) in placed) {
    final writer = primitiveWriters[key]!;
    final type = _pascal(resource) + writer.suffix;
    out
      ..writeln()
      ..writeln('/// `$key` of `$resource`.')
      ..writeln('abstract class $type {')
      ..writeln('  $type._();');
    writer.write(out, resource, value);
    out.writeln('}');
  }
  for (final (resource, view) in views) {
    _viewClass(out, stage, resource, view);
  }
  final notifying = [
    for (final (key, resource, _) in placed)
      if (key == 'x-mana-notifications') resource,
  ];
  if (notifying.isNotEmpty) {
    out
      ..writeln()
      ..writeln(
        '/// Every notice the API declares, so an inbox finds a delivery\'s category and link by its template.',
      )
      ..writeln('abstract class ManaNotices {')
      ..writeln('  ManaNotices._();')
      ..writeln(
        '  static const all = <ManaNotification>[${notifying.map((r) => '...${_pascal(r)}Notifications.all').join(', ')}];',
      )
      ..writeln('}');
  }
  _operations(out, contract);
  File(p.join(stage, 'lib/src/primitives.dart')).writeAsStringSync('$out');
  final library = File(p.join(stage, 'lib/$name.dart'));
  library.writeAsStringSync(
    "${library.readAsStringSync().trimRight()}\nexport 'package:$name/src/primitives.dart';\n",
  );
  final pubspec = File(p.join(stage, 'pubspec.yaml'));
  final package = p.relative(
    p.join(frameworkRoot(), 'flutter/mana_primitives'),
    from: output,
  );
  pubspec.writeAsStringSync(
    pubspec.readAsStringSync().replaceFirst(
      RegExp(r'\ndependencies:\n'),
      '\ndependencies:\n  mana_primitives:\n    path: $package\n',
    ),
  );
}

/// `ManaOperations.all`: each API operation marked `x-mana-verb`, with the
/// verbs it performs, so a client applies their retry and offline rules by
/// route alone.
void _operations(StringBuffer out, Object? contract) {
  final paths = ((contract as Map?)?['paths'] as Map?) ?? const {};
  final rows = <String>[];
  for (final MapEntry(key: path, value: operations) in paths.entries) {
    if (operations is! Map) continue;
    for (final MapEntry(key: method, value: operation) in operations.entries) {
      final verbs = operation is Map ? operation['x-mana-verb'] : null;
      if (verbs is! List || verbs.isEmpty) continue;
      final refs = [
        for (final qualified in verbs.cast<String>())
          '${_pascal(qualified.split('.').first)}Verbs.${_camel(qualified.split('.').last)}',
      ];
      rows.add(
        "    ManaOperation(method: '${(method as String).toUpperCase()}', path: ${_dartString(path as String)}, verbs: [${refs.join(', ')}]),",
      );
    }
  }
  if (rows.isEmpty) return;
  rows.sort();
  out
    ..writeln()
    ..writeln(
      '/// Each API operation with the verbs it performs (`x-mana-verb`).',
    )
    ..writeln('abstract class ManaOperations {')
    ..writeln('  ManaOperations._();')
    ..writeln('  static const all = <ManaOperation>[')
    ..writeAll(rows.map((row) => '$row\n'))
    ..writeln('  ];')
    ..writeln('}');
}

void _verbs(StringBuffer out, String resource, List<Map> verbs) {
  for (final verb in verbs) {
    out.writeln(
      '  static const ${_camel(verb['name'] as String)} = ManaVerb('
      'resource: ${_dartString(resource)}, '
      'name: ${_dartString(verb['name'] as String)}, '
      'action: ${_dartString(verb['action'] as String)}, '
      'risk: VerbRisk.${verb['risk']}, '
      'idempotent: ${verb['idempotent'] == true}'
      '${verb['retry'] is int && verb['retry'] > 0 ? ', retry: ${verb['retry']}' : ''}'
      '${verb['offline'] == 'queue' ? ', offline: VerbOffline.queue' : ''}'
      '${verb['confirm'] == true && verb['risk'] == 'none' ? ', confirm: true' : ''}'
      '${verb['collection'] == true ? ', collection: true' : ''}'
      '${_optional('from', verb['from'])}'
      '${_optional('external', verb['external'])}'
      '${_optional('inverse', verb['inverse'])}'
      '${_optional('feature', verb['feature'])}'
      '${_optional('describe', verb['describe'])}'
      '${_inputs(verb['inputs'])}'
      ');',
    );
  }
  out.writeln(
    '  static const all = <ManaVerb>[${verbs.map((v) => _camel(v['name'] as String)).join(', ')}];',
  );
}

void _views(StringBuffer out, String resource, List<Map> views) {
  for (final view in views) {
    final fields = (view['fields'] as List).cast<String>();
    out.writeln(
      '  static const ${_camel(view['name'] as String)} = ManaView('
      'resource: ${_dartString(resource)}, '
      'name: ${_dartString(view['name'] as String)}, '
      'fields: [${fields.map(_dartString).join(', ')}], '
      'live: ${view['live'] == true}'
      '${_optional('describe', view['describe'])}'
      ');',
    );
  }
}

/// `<Type><View>View`: a record read as one view declares it, its fields
/// typed as the generated attributes model types them, and the sparse
/// fieldset to ask for (`fields`), so a screen names the view once.
void _viewClass(StringBuffer out, String stage, String resource, Map view) {
  final model = File(
    p.join(stage, 'lib/src/model/${resource}_attributes.dart'),
  );
  if (!model.existsSync()) {
    throw ManaFailure(
      'View ${view['name']} of $resource has no attributes model to type it',
    );
  }
  final typed = {
    for (final match in RegExp(
      r"@BuiltValueField\(wireName: r'(\w+)'\)\s+([\w<>?, ]+?) get (\w+);",
    ).allMatches(model.readAsStringSync()))
      match[1]!: (match[2]!, match[3]!),
  };
  final record = _pascal(resource);
  final name = _camel(view['name'] as String);
  final type = '$record${_pascal(view['name'] as String)}View';
  out
    ..writeln()
    ..writeln(
      '/// `$resource` as its `${view['name']}` view reads it'
      '${view['describe'] is String ? ': ${view['describe']}' : ''}.',
    )
    ..writeln('class $type {')
    ..writeln('  const $type._(this.id, this._attributes);')
    ..writeln()
    ..writeln(
      '  factory $type.of($record record) => $type._(record.id, record.attributes!);',
    )
    ..writeln()
    ..writeln('  static const view = ${record}Views.$name;')
    ..writeln()
    ..writeln('  /// The sparse fieldset that asks the server for this view.')
    ..writeln(
      '  static BuiltMap<String, String> get fields => BuiltMap(view.sparse);',
    )
    ..writeln()
    ..writeln('  final String id;')
    ..writeln('  final ${record}Attributes _attributes;');
  for (final field in (view['fields'] as List).cast<String>()) {
    final (dartType, getter) =
        typed[field] ??
        (throw ManaFailure(
          'View ${view['name']} of $resource names $field, which its attributes model lacks',
        ));
    out.writeln('  $dartType get $getter => _attributes.$getter;');
  }
  out.writeln('}');
}

void _attachments(StringBuffer out, String resource, List<Map> attachments) {
  for (final attachment in attachments) {
    final kinds = [
      for (final kind in (attachment['kinds'] as List).cast<Map>())
        'AttachmentKind(name: ${_dartString(kind['name'] as String)}, '
            'accept: [${(kind['accept'] as List).cast<String>().map(_dartString).join(', ')}], '
            'maxBytes: ${kind['max_bytes'] as int}'
            '${kind['max_side'] is int ? ', maxSide: ${kind['max_side']}' : ''}'
            '${kind['quality'] is int ? ', quality: ${kind['quality']}' : ''})',
    ];
    out.writeln(
      '  static const ${_camel(attachment['attribute'] as String)} = ManaAttachment('
      'resource: ${_dartString(resource)}, '
      'attribute: ${_dartString(attachment['attribute'] as String)}, '
      'many: ${attachment['many'] == true}, '
      '${attachment['max'] is int ? 'max: ${attachment['max']}, ' : ''}'
      'kinds: [${kinds.join(', ')}]'
      ');',
    );
  }
}

void _notifications(StringBuffer out, String resource, List<Map> notices) {
  final names = <String>[];
  for (final notice in notices) {
    var name = _camel(notice['action'] as String);
    for (var n = 2; names.contains(name); n++) {
      name = '${_camel(notice['action'] as String)}$n';
    }
    names.add(name);
    out.writeln(
      '  static const $name = ManaNotification('
      'resource: ${_dartString(resource)}, '
      'action: ${_dartString(notice['action'] as String)}, '
      'template: ${_dartString(notice['template'] as String)}, '
      'category: ${_dartString(notice['category'] as String)}, '
      'channels: [${(notice['channels'] as List).cast<String>().map(_dartString).join(', ')}]'
      '${_optional('opens', notice['opens'])}'
      ');',
    );
  }
  out.writeln('  static const all = <ManaNotification>[${names.join(', ')}];');
}

void _flow(StringBuffer out, String resource, List<Map> value) {
  final flow = value.single;
  final steps = [
    for (final step in (flow['steps'] as List).cast<Map>())
      'FlowStep(name: ${_dartString(step['name'] as String)}, '
          'action: ${_dartString(step['action'] as String)}'
          '${step['optional'] == true ? ', optional: true' : ''}'
          '${step['skippable'] == true ? ', skippable: true' : ''})',
  ];
  out.writeln(
    '  static const flow = ManaFlow('
    'resource: ${_dartString(resource)}, '
    'cursor: ${_dartString(flow['cursor'] as String)}, '
    'done: ${_dartString(flow['done'] as String)}, '
    'steps: [${steps.join(', ')}]'
    ');',
  );
}

void _history(StringBuffer out, String resource, List<Map> value) {
  final history = value.single;
  out.writeln(
    '  static const history = ManaHistory('
    'resource: ${_dartString(resource)}'
    '${_optional('log', history['log'])}, '
    'redacted: [${(history['redacted'] as List? ?? const []).cast<String>().map(_dartString).join(', ')}]'
    ');',
  );
}

void _entity(StringBuffer out, String resource, List<Map> value) {
  final entity = value.single;
  List<String> names(String key) =>
      (entity[key] as List? ?? const []).cast<String>();
  out.writeln(
    '  static const entity = ManaEntity('
    'resource: ${_dartString(resource)}, '
    'topic: ${_dartString(entity['topic'] as String? ?? resource)}, '
    'audience: [${names('audience').map(_dartString).join(', ')}], '
    'deadlines: [${names('deadlines').map(_dartString).join(', ')}]'
    '${entity['watchable'] == true ? ', watchable: true' : ''}'
    ');',
  );
}

String _inputs(Object? inputs) => inputs is List && inputs.isNotEmpty
    ? ', inputs: [${inputs.cast<Map>().map(_input).join(', ')}]'
    : '';

String _input(Map input) {
  String number(String key) =>
      input[key] is num ? ', ${_camel(key)}: ${input[key]}' : '';
  return 'VerbInput('
      'name: ${_dartString('${input['name'] ?? ''}')}, '
      'type: ${_dartString(input['type'] as String)}'
      '${input['required'] == true ? ', required: true' : ''}'
      '${input['min_length'] is int ? ', minLength: ${input['min_length']}' : ''}'
      '${input['max_length'] is int ? ', maxLength: ${input['max_length']}' : ''}'
      '${_optional('match', input['match'])}'
      '${number('min')}${number('max')}'
      '${input['one_of'] is List ? ', oneOf: [${(input['one_of'] as List).cast<String>().map(_dartString).join(', ')}]' : ''}'
      '${_optional('format', input['format'])}'
      '${input['items'] is Map ? ', items: ${_input({'name': input['name'], ...input['items'] as Map})}' : ''}'
      '${input['unique'] == true ? ', unique: true' : ''}'
      ')';
}

String _optional(String name, Object? value) =>
    value is String ? ', $name: ${_dartString(value)}' : '';

String _dartString(String value) =>
    '"${value.replaceAll('\\', r'\\').replaceAll('"', r'\"').replaceAll(r'$', r'\$')}"';

String _camel(String value) {
  final parts = value.split(RegExp('[_-]'));
  return parts.first +
      parts
          .skip(1)
          .map((s) => s.isEmpty ? s : s[0].toUpperCase() + s.substring(1))
          .join();
}

String _pascal(String value) {
  final camel = _camel(value);
  return camel[0].toUpperCase() + camel.substring(1);
}

/// What keeps the primitives in [contract] (its `info.x-mana-primitives`)
/// from being whole: a contract key without a client writer, or a catalog
/// id missing from [catalogIds] (so agents would never find it).
List<String> primitiveGaps(Object? contract, Set<String> catalogIds) {
  final listed =
      (((contract as Map?)?['info'] as Map?)?['x-mana-primitives'] as List?)
          ?.cast<Map>() ??
      const <Map>[];
  return [
    for (final primitive in listed) ...[
      if (!primitiveWriters.containsKey(primitive['contract']))
        '${primitive['contract']} has no client writer',
      if (!catalogIds.contains(primitive['catalog']))
        '${primitive['contract']} names catalog id ${primitive['catalog']}, which framework/catalog.toml lacks',
    ],
  ];
}

/// The contracts generated clients were built from (`<package>/.mana/contract.json`).
List<File> generatedContracts(String root) => [
  for (final top in ['packages', 'apps'])
    if (Directory(p.join(root, top)).existsSync())
      for (final package in Directory(p.join(root, top)).listSync())
        if (File(p.join(package.path, '.mana/contract.json')) case final file
            when file.existsSync())
          file,
];
