/// The client half of Mana primitives, declared once in Ash: the verbs a
/// resource offers (`Mana.Verbs`), the views its screens read (`Mana.Views`)
/// and the files it holds (`Mana.Attachments`).
///
/// The API client generated by `mana client generate` exposes them as
/// constants (`BookingVerbs.cancel`, `BookingViews.reservationCard`,
/// `PropertyAttachments.coverPhotoId`) and every record carries the verbs it
/// offers the actor now (`booking.verbs`). Interfaces ask
/// [ManaVerb.offeredBy] instead of re-deriving "can I do X" from a status,
/// and [ManaAttachment.reject] before uploading a file the server would refuse.
library;

/// What a verb does without a network: fail at once, or wait in the
/// client's queue (only idempotent verbs that move no money may).
enum VerbOffline {
  reject,
  queue;

  static VerbOffline parse(String? value) =>
      value == 'queue' ? VerbOffline.queue : VerbOffline.reject;
}

/// How carefully an interface performs a verb.
enum VerbRisk {
  none,

  /// Moves money: confirm first.
  money,

  /// Cannot be undone: confirm first.
  destructive;

  static VerbRisk parse(String value) =>
      values.firstWhere((v) => v.name == value, orElse: () => none);

  bool get confirms => this != none;
}

/// An API operation and the verbs it performs, from its `x-mana-verb`: how a
/// client knows, by route alone, whether a call may be resent or wait offline.
final class ManaOperation {
  const ManaOperation({
    required this.method,
    required this.path,
    required this.verbs,
  });

  /// `GET`, `POST`, `PATCH` or `DELETE`.
  final String method;

  /// The route template, e.g. `/api/operations/bookings/{id}/cancel`.
  final String path;
  final List<ManaVerb> verbs;

  /// Whether a request to [requestPath] with [requestMethod] is this
  /// operation; a `{param}` segment matches any one segment.
  bool matches(String requestMethod, String requestPath) {
    if (requestMethod.toUpperCase() != method) return false;
    final want = path.split('/');
    final got = Uri.parse(requestPath).path.split('/');
    if (want.length != got.length) return false;
    for (var i = 0; i < want.length; i++) {
      if (want[i].startsWith('{') && want[i].endsWith('}')) continue;
      if (want[i] != got[i]) return false;
    }
    return true;
  }

  /// The operation among [operations] that [method] [path] performs.
  static ManaOperation? of(
    Iterable<ManaOperation> operations,
    String method,
    String path,
  ) {
    for (final operation in operations) {
      if (operation.matches(method, path)) return operation;
    }
    return null;
  }

  /// The retry the verbs allow: the least of them (one that is not
  /// idempotent allows none).
  int get retry => verbs.isEmpty
      ? 0
      : verbs
            .map((verb) => verb.idempotent ? verb.retry : 0)
            .reduce((a, b) => a < b ? a : b);

  /// Whether every verb may wait in an offline queue.
  bool get queues =>
      verbs.isNotEmpty &&
      verbs.every((verb) => verb.offline == VerbOffline.queue);
}

final class ManaVerb {
  const ManaVerb({
    required this.resource,
    required this.name,
    required this.action,
    this.risk = VerbRisk.none,
    this.inverse,
    this.idempotent = false,
    this.feature,
    this.describe,
    this.inputs = const [],
    this.retry = 0,
    this.offline = VerbOffline.reject,
    bool confirm = false,
    this.collection = false,
    this.from,
    this.external,
  }) : _confirm = confirm;

  /// The JSON:API type, e.g. `booking`.
  final String resource;

  /// The verb as the server names it, e.g. `accept_proposal`.
  final String name;

  /// The resource action it performs.
  final String action;
  final VerbRisk risk;

  /// The verb that undoes this one.
  final String? inverse;
  final bool idempotent;

  /// Its `feature:<name>` address.
  final String? feature;
  final String? describe;

  /// What the action takes, with the rules the server enforces.
  final List<VerbInput> inputs;

  /// Times a client resends it after a transient failure (idempotent verbs).
  final int retry;

  /// What happens without a network.
  final VerbOffline offline;

  final bool _confirm;

  /// Offered with no record of its own: creating one, or acting on the
  /// person's account. With [from], a parent record offers it.
  final bool collection;

  /// The type of the parent record that offers this collection verb.
  final String? from;

  /// The outside system its action reaches (`stripe`, `email`, `sms`): what
  /// it does there cannot be rolled back, so a client never queues it.
  final String? external;

  /// How lists of offered verbs name a collection verb: `booking.request`.
  String get qualified => '$resource.$name';

  /// Whether a client asks before running it: it moves money or cannot be
  /// undone, or its declaration says `confirm: true`.
  bool get confirms => _confirm || risk.confirms;

  /// The input named [name] as the API spells it.
  VerbInput input(String name) => inputs.firstWhere(
    (i) => i.name == name,
    orElse: () => throw ArgumentError('$this takes no input $name'),
  );

  /// Whether [offered] (a record's `verbs`, or what the person may start)
  /// includes it.
  bool offeredBy(Iterable<String>? offered) =>
      offered?.contains(collection ? qualified : name) ?? false;

  @override
  String toString() => '$resource.$name';
}

/// What one screen reads from a resource (`Mana.Views`): the declared fields,
/// and the JSON:API sparse fieldset that asks the server for only those.
final class ManaView {
  const ManaView({
    required this.resource,
    required this.name,
    required this.fields,
    this.live = false,
    this.describe,
  });

  final String resource;
  final String name;

  /// Attribute names as the API spells them.
  final List<String> fields;

  /// The screen follows `Mana.Entity` announcements.
  final bool live;
  final String? describe;

  /// The `fields` query parameter for a read of [resource].
  Map<String, String> get sparse => {resource: fields.join(',')};

  @override
  String toString() => '$resource:$name';
}

/// An upload kind an attachment accepts, with the server's limits.
final class AttachmentKind {
  const AttachmentKind({
    required this.name,
    required this.accept,
    required this.maxBytes,
  });

  /// The kind as the API spells it (`property_photo`).
  final String name;

  /// Accepted content types (`image/jpeg`).
  final List<String> accept;
  final int maxBytes;
}

/// A resource attribute that holds uploaded files (`Mana.Attachments`).
final class ManaAttachment {
  const ManaAttachment({
    required this.resource,
    required this.attribute,
    required this.kinds,
    this.many = false,
    this.max,
  });

  final String resource;

  /// The attribute as the API spells it (`cover_photo_id`).
  final String attribute;

  /// Whether it holds a list of files.
  final bool many;

  /// How many files a list holds at most (the attribute's `max_length`).
  final int? max;
  final List<AttachmentKind> kinds;

  /// The kind uploads for this attachment are requested as.
  AttachmentKind get kind => kinds.first;

  /// The error code the server would answer for this file, or null when it
  /// would take it: `upload.content_type_invalid` or `upload.size_too_large`.
  String? reject({required String contentType, required int sizeBytes}) {
    if (!kind.accept.contains(contentType))
      return 'upload.content_type_invalid';
    if (sizeBytes <= 0 || sizeBytes > kind.maxBytes) {
      return 'upload.size_too_large';
    }
    return null;
  }

  @override
  String toString() => '$resource.$attribute';
}

/// One input of a verb with the server's rules for it, so a client refuses
/// what the server would refuse before sending. The server stays
/// authoritative.
final class VerbInput {
  const VerbInput({
    required this.name,
    required this.type,
    this.required = false,
    this.minLength,
    this.maxLength,
    this.match,
    this.min,
    this.max,
    this.oneOf,
    this.format,
    this.items,
    this.unique = false,
  });

  /// As the API spells it (`counter_note`).
  final String name;

  /// `string`, `integer`, `number`, `boolean`, `array` or `object`.
  final String type;
  final bool required;
  final int? minLength;
  final int? maxLength;

  /// A regular expression the whole value must match.
  final String? match;
  final num? min;
  final num? max;
  final List<String>? oneOf;

  /// `uuid`, `date-time`, `date` or a `Mana.BR` format (`br-cpf`, `br-cnpj`, `br-cep`, `br-phone`,
  /// `br-plate`).
  final String? format;

  /// The rules of each element of an `array`.
  final VerbInput? items;

  /// No two records may hold the same value (an identity on the server);
  /// a form can ask early, the server still decides.
  final bool unique;

  /// Why the server would refuse [value], or null when it would take it:
  /// `required`, `too_short`, `too_long`, `too_small`, `too_large`,
  /// `pattern`, `one_of`, `type` or `format`. [formats] checks named formats
  /// (`mana_br` supplies the Brazilian ones); a format without a checker is
  /// left to the server.
  String? check(
    Object? value, {
    Map<String, bool Function(String)> formats = const {},
  }) {
    if (value == null || (value is String && value.trim().isEmpty)) {
      return required ? 'required' : null;
    }
    switch (type) {
      case 'string':
        if (value is DateTime) {
          return format == 'date-time' || format == 'date' ? null : 'type';
        }
        if (value is! String) return 'type';
        if (minLength case final min? when value.runes.length < min) {
          return 'too_short';
        }
        if (maxLength case final max? when value.runes.length > max) {
          return 'too_long';
        }
        if (match case final pattern? when !RegExp(pattern).hasMatch(value)) {
          return 'pattern';
        }
        if (oneOf case final options? when !options.contains(value)) {
          return 'one_of';
        }
        if (format case final name?) {
          final valid = name == 'date-time' || name == 'date'
              ? DateTime.tryParse(value) != null
              : name == 'uuid'
              ? _uuid.hasMatch(value)
              : formats[name]?.call(value);
          if (valid == false) return 'format';
        }
      case 'integer' || 'number':
        final number = value is num ? value : num.tryParse('$value'.trim());
        if (number == null ||
            (type == 'integer' &&
                number is! int &&
                number != number.roundToDouble())) {
          return 'type';
        }
        if (min case final low? when number < low) return 'too_small';
        if (max case final high? when number > high) return 'too_large';
      case 'array':
        if (value is! List) return 'type';
        if (minLength case final min? when value.length < min)
          return 'too_short';
        if (maxLength case final max? when value.length > max)
          return 'too_long';
        for (final element in value) {
          if (items?.check(element, formats: formats) case final code?) {
            return code;
          }
        }
      case 'boolean':
        if (value is! bool) return 'type';
    }
    return null;
  }

  static final _uuid = RegExp(
    r'^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$',
  );

  @override
  String toString() => name;
}

/// The input each JSON:API error in [body] points at
/// (`source.pointer: /data/attributes/<name>`, or `field`), with its code,
/// so a form shows the server's refusal on the field that caused it.
Map<String, String> verbFieldErrors(Object? body) {
  final errors = body is Map ? body['errors'] : null;
  return {
    if (errors is List)
      for (final error in errors.whereType<Map>())
        if (_field(error) case final field?)
          field: '${error['code'] ?? 'invalid'}',
  };
}

String? _field(Map error) {
  final pointer = (error['source'] as Map?)?['pointer'];
  if (pointer is String) {
    final segments = pointer.split('/').where((s) => s.isNotEmpty).toList();
    if (segments.length >= 3 &&
        segments[0] == 'data' &&
        (segments[1] == 'attributes' || segments[1] == 'arguments')) {
      return segments[2];
    }
  }
  final field = error['field'];
  return field is String ? field : null;
}

/// A resource whose changes are recorded (`Mana.History`): read a record's
/// entries from [log]'s `of` action.
/// A live resource (`Mana.Entity`): its changes are announced on
/// `entity:<topic>:<id>` and, for each [audience] field's user,
/// `entity:<topic>:for:<user>`; `mana_live`'s `LiveEntity.of` follows them.
final class ManaEntity {
  const ManaEntity({
    required this.resource,
    required this.topic,
    this.audience = const [],
    this.deadlines = const [],
    this.watchable = false,
  });

  final String resource;
  final String topic;

  /// Whether some people (its `watchers`) may follow every record of it.
  final bool watchable;

  /// User-id fields whose user hears every change.
  final List<String> audience;

  /// Deadlines that change the record on their own, with no request.
  final List<String> deadlines;
}

final class ManaHistory {
  const ManaHistory({
    required this.resource,
    this.log,
    this.redacted = const [],
  });

  final String resource;

  /// The JSON:API type of the log resource.
  final String? log;

  /// Inputs and attributes that entries show only as `[redacted]`.
  final List<String> redacted;
}

/// Who made a change.
enum HistoryActor { user, system, agent }

/// One recorded change, as the log serves it.
final class ManaHistoryEntry {
  const ManaHistoryEntry({
    required this.action,
    required this.summary,
    required this.actor,
    required this.at,
    this.verb,
    this.actorId,
    this.via,
    this.failed = false,
    this.error,
    this.params = const {},
    this.before = const {},
    this.after = const {},
  });

  /// From an entry's JSON:API `attributes`.
  factory ManaHistoryEntry.fromJson(Map attributes) => ManaHistoryEntry(
    action: '${attributes['action']}',
    summary: '${attributes['summary']}',
    actor: HistoryActor.values.byName('${attributes['actor_kind']}'),
    at: DateTime.parse('${attributes['at']}'),
    verb: attributes['verb'] as String?,
    actorId: attributes['actor_id'] as String?,
    via: attributes['via'] as String?,
    failed: attributes['outcome'] == 'failed',
    error: attributes['error'] as String?,
    params: (attributes['params'] as Map?)?.cast<String, Object?>() ?? const {},
    before: (attributes['before'] as Map?)?.cast<String, Object?>() ?? const {},
    after: (attributes['after'] as Map?)?.cast<String, Object?>() ?? const {},
  );

  final String action;

  /// The verb's `narrate:` sentence, or the action's name.
  final String summary;
  final HistoryActor actor;
  final DateTime at;
  final String? verb;
  final String? actorId;

  /// The agent's name, or `deadline:<name>` for a system deadline.
  final String? via;
  final bool failed;
  final String? error;
  final Map<String, Object?> params;
  final Map<String, Object?> before;
  final Map<String, Object?> after;

  /// The attributes the change moved, with their old and new values.
  Map<String, (Object?, Object?)> get changes => {
    for (final key in {...before.keys, ...after.keys})
      key: (before[key], after[key]),
  };
}

/// One step of a [ManaFlow].
final class FlowStep {
  const FlowStep({
    required this.name,
    required this.action,
    this.optional = false,
    this.skippable = false,
  });

  /// The cursor value while this step is current.
  final String name;

  /// The action that completes it.
  final String action;
  final bool optional;

  /// The server passes over it when its condition holds.
  final bool skippable;
}

/// A journey kept on the record (`Mana.Flow`): the server moves its
/// [cursor]; interfaces only show where it stands.
final class ManaFlow {
  const ManaFlow({
    required this.resource,
    required this.cursor,
    required this.done,
    required this.steps,
  });

  final String resource;

  /// The attribute holding the current step.
  final String cursor;

  /// The cursor value once every step is complete.
  final String done;
  final List<FlowStep> steps;

  /// The step [current] names, or null when done or outside the flow.
  FlowStep? stepOf(String? current) =>
      steps.where((s) => s.name == current).firstOrNull;

  bool isDone(String? current) => current == done;

  /// Zero-based position of [current]: `steps.length` when done, 0 when
  /// outside the flow.
  int indexOf(String? current) {
    if (isDone(current)) return steps.length;
    final index = steps.indexWhere((s) => s.name == current);
    return index < 0 ? 0 : index;
  }

  /// From 0 to 1.
  double progress(String? current) =>
      steps.isEmpty ? 1 : indexOf(current) / steps.length;
}

/// A notice a resource sends after an action (`Mana.Notifications`).
final class ManaNotification {
  const ManaNotification({
    required this.resource,
    required this.action,
    required this.template,
    this.category = 'general',
    this.channels = const ['inbox'],
    this.opens,
  });

  final String resource;
  final String action;
  final String template;

  /// What a person turns on or off together.
  final String category;
  final List<String> channels;

  /// The deep link it opens, with `:id` for the record.
  final String? opens;

  /// The link for a notice whose payload names the record
  /// (`{"booking_id": ...}`), or null.
  String? link(Map payload) {
    final id = payload['${resource}_id'];
    return opens == null || id == null
        ? null
        : opens!.replaceAll(':id', Uri.encodeComponent('$id'));
  }

  /// The declaration among [all] that sends [template].
  static ManaNotification? of(
    Iterable<ManaNotification> all,
    String template,
  ) => all.where((n) => n.template == template).firstOrNull;
}
