name: __name___app
description: The __name__ app.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  live_ui:
    path: ../mana/framework/flutter/live_ui
  __name___api:
    path: ../packages/api
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
