FROM elixir@sha256:09b37446f1b24a280890c4b294eec6a53ba2501a2289959b483d849035e1053c
RUN apt-get update && apt-get install -y --no-install-recommends build-essential git ca-certificates \
    && rm -rf /var/lib/apt/lists/*
