defmodule Mana.Presentation.Dart do
  @moduledoc "Emits ordinary Flutter widgets with typed submission and optional field builders."
  def render(contract) do
    """
    // GENERATED by mana.forms; edit the Elixir declaration or a Dart field builder.
    // Resource: #{contract.resource}
    #{if Enum.any?(contract.forms, fn form -> Enum.any?(form.inputs, &(Map.get(&1, :count) == "bytes")) end), do: "import 'dart:convert';", else: ""}
    import 'package:flutter/material.dart';
    #{contract.forms |> Enum.map(& &1.binding) |> Enum.reject(&is_nil/1) |> Enum.map(& &1.package) |> Enum.uniq() |> Enum.map_join("\n", &"import 'package:#{&1}/#{&1}.dart' as api;")}

    #{Enum.map_join(contract.forms, "\n", &render_form/1)}
    """
  end

  defp render_form(form) do
    class = form.name |> Macro.camelize()
    fields = form.inputs

    """
    #{render_action(form)}
    final class #{class}Copy {
      const #{class}Copy({this.submit = #{dart_string(form.submit)}, this.failure = #{dart_string(form.failure)},
        #{Enum.map_join(fields, "\n", &"this.#{camel(&1.name)}Label = #{dart_string(&1.label)}, this.#{camel(&1.name)}Invalid = #{dart_string(&1.invalid)},")}
      });
      final String submit;
      final String failure;
      #{Enum.map_join(fields, "\n", &"final String #{camel(&1.name)}Label; final String #{camel(&1.name)}Invalid;")}
    }

    final class #{class}Input {
      const #{class}Input({#{Enum.map_join(fields, ", ", &"required this.#{camel(&1.name)}")}});
      #{Enum.map_join(fields, "\n", &"final #{if &1.type == "integer", do: "int", else: "String"}#{if &1.required, do: "", else: "?"} #{camel(&1.name)};")}
    }

    final class #{class}Form extends StatefulWidget {
      const #{class}Form({required this.onSubmit, this.busy = false, this.failure, this.copy = const #{class}Copy(),
        #{Enum.map_join(fields, "\n", &"this.#{camel(&1.name)}Controller, this.#{camel(&1.name)}Builder,")}
        super.key});
      final Future<bool> Function(#{class}Input input) onSubmit;
      final #{class}Copy copy;
      final bool busy;
      final String? failure;
      #{Enum.map_join(fields, "\n", fn field ->
      name = camel(field.name)
      "final TextEditingController? #{name}Controller;\nfinal Widget Function(BuildContext, TextFormField)? #{name}Builder;"
    end)}
      @override
      State<#{class}Form> createState() => _#{class}FormState();
    }

    final class _#{class}FormState extends State<#{class}Form> {
      final _form = GlobalKey<FormState>();
      bool _submitting = false;
      String? _failure;
      #{Enum.map_join(fields, "\n", fn field ->
      name = camel(field.name)
      "late TextEditingController _#{name} = widget.#{name}Controller ?? TextEditingController();"
    end)}
      #{Enum.map_join(fields, "\n", &validation/1)}
      Future<void> _submit() async {
        if (_submitting || widget.busy || !_form.currentState!.validate()) { return; }
        // A custom builder cannot bypass action-input validation.
        if (#{Enum.map_join(fields, " || ", &"_validate#{Macro.camelize(&1.name)}(_#{camel(&1.name)}.text) != null")}) { return; }
        #{Enum.map_join(fields, "\n", &"final before#{Macro.camelize(&1.name)} = _#{camel(&1.name)}.text;")}
        final input = #{class}Input(
          #{Enum.map_join(fields, "\n", &"#{camel(&1.name)}: _normalize#{Macro.camelize(&1.name)}(_#{camel(&1.name)}.text)#{if &1.required, do: "!", else: ""},")}
        );
        setState(() { _submitting = true; _failure = null; });
        try {
          final accepted = await widget.onSubmit(input);
          if (!mounted) { return; }
          if (accepted) {
            #{Enum.map_join(fields, "\n", &"if (_#{camel(&1.name)}.text == before#{Macro.camelize(&1.name)}) { _#{camel(&1.name)}.clear(); }")}
          } else {
            _failure = widget.copy.failure;
          }
        } on Object {
          if (mounted) { _failure = widget.copy.failure; }
        } finally {
          if (mounted) { setState(() => _submitting = false); }
        }
      }
      @override
      void didUpdateWidget(covariant #{class}Form oldWidget) {
        super.didUpdateWidget(oldWidget);
        #{Enum.map_join(fields, "\n", fn field ->
      name = camel(field.name)
      """
      if (oldWidget.#{name}Controller != widget.#{name}Controller) {
        final previous = _#{name}.text;
        if (oldWidget.#{name}Controller == null) { _#{name}.dispose(); }
        _#{name} = widget.#{name}Controller ?? TextEditingController(text: previous);
      }
      """
    end)}
      }
      @override
      void dispose() {
        #{Enum.map_join(fields, "\n", &"if (widget.#{camel(&1.name)}Controller == null) { _#{camel(&1.name)}.dispose(); }")}
        super.dispose();
      }
      @override
      Widget build(BuildContext context) {
        final busy = widget.busy || _submitting;
        final failure = widget.failure ?? _failure;
        return Form(key: _form, child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            #{Enum.map_join(fields, "\n", &control/1)}
            FilledButton(key: const ValueKey(#{dart_string(form.submit_key)}),
              onPressed: busy ? null : _submit, child: Text(widget.copy.submit)),
            if (failure != null) Semantics(liveRegion: true, child: Text(failure)),
          ],
        ));
      }
    }
    """
  end

  defp render_action(%{binding: nil}), do: ""

  defp render_action(form) do
    binding = form.binding
    class = Macro.camelize(form.name)

    """
    /// Uses the generated SDK and the caller's authenticated transport.
    /// A receipt acknowledges the write; subsequent UI refresh is separate.
    final class #{class}Action {
      const #{class}Action(this.client#{if binding.update, do: ", {required this.id}", else: ""});
      final api.#{binding.api} client;
      #{if binding.update, do: "final String id;", else: ""}
      Future<api.#{binding.record}> call(#{class}Input input#{if binding.create_identity, do: ", {required String creationId}", else: ""}) async {
        #{if binding.create_identity, do: "if (!RegExp(r'^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$').hasMatch(creationId)) { throw const FormatException('Expected a UUID v4 creation identity'); }", else: ""}
        #{if binding.update, do: "if (id.isEmpty) { throw const FormatException('Missing record identity'); }", else: ""}
        final response = await client.#{binding.operation}(
          #{if binding.update, do: "id: id,", else: ""}
          #{camel(binding.request)}: api.#{binding.request}((b) {
            b.data.type = api.#{binding.request}DataTypeEnum.#{binding.enum_value};
            #{if binding.update, do: "b.data.id = id;", else: ""}
            #{if binding.create_identity, do: "b.data.attributes.#{camel(binding.create_identity)} = creationId;", else: ""}
            #{Enum.map_join(form.inputs, "\n", &"b.data.attributes.#{camel(&1.name)} = input.#{camel(&1.name)};")}
          }),
        );
        final record = response.data?.data;
        if (response.statusCode != #{binding.status} || record == null || record.id.isEmpty ||
            record.type != #{dart_string(binding.resource_type)}#{if binding.update, do: " || record.id != id", else: ""}#{if binding.create_identity, do: " || record.id != creationId", else: ""}) {
          throw const FormatException('Missing action acknowledgement');
        }
        return record;
      }
    }

    """
  end

  defp validation(%{type: "integer"} = field) do
    name = Macro.camelize(field.name)
    invalid = "widget.copy.#{camel(field.name)}Invalid"
    """
    int? _normalize#{name}(String raw) {
      final value = raw.trim();
      if (!RegExp(r'^[+-]?[0-9]+$').hasMatch(value)) { return null; }
      return int.tryParse(value, radix: 10);
    }
    String? _validate#{name}(String? raw) {
      if ((raw ?? '').trim().isEmpty) { return #{if field.required, do: invalid, else: "null"}; }
      final value = _normalize#{name}(raw!);
      if (value == null || value < #{field.min} || value > #{field.max}) { return #{invalid}; }
      return null;
    }
    """
  end

  defp validation(field) do
    name = Macro.camelize(field.name)

    length =
      case field.count do
        "codepoints" -> "value.runes.length"
        "bytes" -> "utf8.encode(value).length"
        "graphemes" -> "value.characters.length"
      end

    tests =
      []
      |> then(fn tests ->
        if field.min,
          do:
            tests ++ [if(field.min == 1, do: "value.isEmpty", else: "#{length} < #{field.min}")],
          else: tests
      end)
      |> then(fn tests ->
        if field.max,
          do:
            tests ++
              [if(field.max == 0, do: "value.isNotEmpty", else: "#{length} > #{field.max}")],
          else: tests
      end)

    """
    String? _normalize#{name}(String raw) {
      final value = #{if field.trim, do: "raw.trim()", else: "raw"};
      return #{if field.allow_empty, do: "value", else: "value.isEmpty ? null : value"};
    }
    String? _validate#{name}(String? raw) {
      final value = _normalize#{name}(raw ?? '');
      if (value == null) { return #{if field.required, do: "widget.copy.#{camel(field.name)}Invalid", else: "null"}; }
      #{if tests != [], do: "if (#{Enum.join(tests, " || ")}) { return widget.copy.#{camel(field.name)}Invalid; }", else: ""}
      return null;
    }
    """
  end

  defp control(field) do
    name = camel(field.name)

    widget =
      """
      TextFormField(
        key: const ValueKey(#{dart_string(field.key)}), controller: _#{name}, enabled: !busy,
        decoration: InputDecoration(labelText: widget.copy.#{name}Label, border: const OutlineInputBorder()),
        obscureText: #{field.sensitive}, autocorrect: #{!field.sensitive}, enableSuggestions: #{!field.sensitive},
        #{if field.type == "integer", do: "keyboardType: const TextInputType.numberWithOptions(signed: #{field.min < 0}),", else: ""}
        textInputAction: TextInputAction.done, onFieldSubmitted: (_) => _submit(),
        validator: _validate#{Macro.camelize(field.name)},
      )
      """
      |> String.trim()

    """
    widget.#{name}Builder?.call(context, #{widget}) ?? #{widget},
    const SizedBox(height: 8),
    """
  end

  defp camel(value) do
    <<first::utf8, rest::binary>> = Macro.camelize(value)
    String.downcase(<<first::utf8>>) <> rest
  end

  defp dart_string(value), do: value |> Jason.encode!() |> String.replace("$", "\\$")
end
